<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-03T23:39:49 IST" name="Suite" finished-at="2021-07-03T23:39:49 IST" duration-ms="100">
    <groups>
    </groups>
    <test started-at="2021-07-03T23:39:49 IST" name="Test" finished-at="2021-07-03T23:39:49 IST" duration-ms="100">
      <class name="ForPractice.MavenPractice.RestAPITest">
        <test-method signature="RestAPITest1()[pri:0, instance:ForPractice.MavenPractice.RestAPITest@3e6ef8ad]" started-at="2021-07-03T23:39:49 IST" name="RestAPITest1" finished-at="2021-07-03T23:39:49 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RestAPITest1 -->
        <test-method signature="RestAPITest2()[pri:0, instance:ForPractice.MavenPractice.RestAPITest@3e6ef8ad]" started-at="2021-07-03T23:39:49 IST" name="RestAPITest2" finished-at="2021-07-03T23:39:49 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RestAPITest2 -->
      </class> <!-- ForPractice.MavenPractice.RestAPITest -->
      <class name="ForPractice.MavenPractice.AppiumTest">
        <test-method signature="Appium1()[pri:0, instance:ForPractice.MavenPractice.AppiumTest@59af0466]" started-at="2021-07-03T23:39:49 IST" name="Appium1" finished-at="2021-07-03T23:39:49 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Appium1 -->
        <test-method signature="Appium2()[pri:0, instance:ForPractice.MavenPractice.AppiumTest@59af0466]" started-at="2021-07-03T23:39:49 IST" name="Appium2" finished-at="2021-07-03T23:39:49 IST" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at ForPractice.MavenPractice.AppiumTest.Appium2(AppiumTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Appium2 -->
      </class> <!-- ForPractice.MavenPractice.AppiumTest -->
      <class name="ForPractice.MavenPractice.seleniumTest">
        <test-method signature="selenium1()[pri:0, instance:ForPractice.MavenPractice.seleniumTest@346d61be]" started-at="2021-07-03T23:39:49 IST" name="selenium1" finished-at="2021-07-03T23:39:49 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selenium1 -->
        <test-method signature="selenium2()[pri:0, instance:ForPractice.MavenPractice.seleniumTest@346d61be]" started-at="2021-07-03T23:39:49 IST" name="selenium2" finished-at="2021-07-03T23:39:49 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selenium2 -->
      </class> <!-- ForPractice.MavenPractice.seleniumTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
